version: 2

sources:
  - name: source_bq
    database: de-projects-453518 #Replace with your GCP project id, specified in "gcp_project_id" task of "1_gcp_kv.yml" file
    schema: web_logs_dataset # Replace with your BQ dataset name, specified in "gcp_dataset" task of "1_gcp_kv.yml" file

    tables:
      - name: web_logs

models:
  - name: fraud_detected
    description: "Fraudulent IPs that fulfilled all 3 different types of suspicious activity. Criteria are in the column description."
    columns:
      - name: ip
        data_type: string
        description: "Fraudelent IP address"

      - name: requests_per_second
        data_type: integer
        description: "Frequency requests more than 3 times during 1 second (times per second)"

      - name: requests_per_day_from_3_account_types
        data_type: integer
        description: "Logged in with 3 different account types during 1 day (times per day)"

      - name: sessions_q75_duration_bytes
        data_type: integer
        description: "Sessions where the IP address's consumed bytes AND duration time exceed 75% of all users. Such exceeding was repeated more than once (sessions over all time)"

  - name: RFM_analysis
    description: "Calculates RFM scores and assigns users to segments based on their engagement and spending behavior. Fraudulent traffic is excluded to ensure data accuracy."
    columns:
      - name: ip
        data_type: string
        description: "User's IP address"

      - name: last_login_days_ago
        data_type: integer
        description: "Recency: The number of days since the user's last login, measured from the dataset's latest date"

      - name: logins_per_week
        data_type: integer
        description: "Frequency: The number of logins in the past week"

      - name: spent_per_week
        data_type: float64
        description: "Monetary: The total amount spent (EUR) in the past week"

      - name: user_value
        data_type: string
        description: "User segment based on RFM scores: high, mid, or low-value users"

  - name: user_segmentation
    description: "Segmentation of users based on RFM scores. Provides insights into segment distribution by country, along with average age and gender composition"
    columns:
      - name: country
        data_type: string
        description: "2-digit country code. Repeats once for each user segment"

      - name: user_value
        data_type: string
        description: "User segmentation based on their RFM values. Users are divided into 3 segments: high-, mid-, and low-valuable users"

      - name: user_value_share_per_country
        data_type: float64
        description: "The percentage of users in this segment within each country"

      - name: avg_age
        data_type: float64
        description: "The average age of users in this segment for each country"

      - name: percentage_male
        data_type: float64
        description: "Percentage of male users in this segment within each country"

      - name: percentage_female
        data_type: float64
        description: "Percentage of female users in this segment within each country"

  - name: user_behavior_by_account_type
    description: "Analysis of user accounts segmented by account type. Provides insights into total accounts, average lifetime value (LTV), ARPU, weekly retention rate, and refund rate based on user behavior and attributes."
    columns:
      - name: account_type
        data_type: string
        description: "The type of user account. Includes values such as 'Premium', 'Normal', and 'Not Logged In'."

      - name: total_accounts
        data_type: int64
        description: "The total number of accounts within each account type segment."

      - name: avg_LTV
        data_type: float64
        description: "The average lifetime value (LTV) of users within each account type segment. It reflects the total revenue generated per user over their lifetime."

      - name: ARPU_per_day
        data_type: float64
        description: "The average revenue per user per day (ARPU) for each account type segment. Calculated as the total revenue per user divided by the number of active days."

      - name: retention_rate_per_week
        data_type: float64
        description: "The weekly retention rate for each account type segment. It measures the percentage of users who return to the platform within the first 7 days after their first visit."

      - name: refund_rate
        data_type: float64
        description: "The refund rate for each account type segment. It is the percentage of total refunded amount relative to the total sales for the segment."
